var lastModified = new Date("2023-09-30T12:00:00+0000");
var equipment_data = {};
var equipment = [
    {
        make: 'Martin',
        model: 'HD-28E Retro',
        category: 'Instruments',
        type: 'Acoustic Guitar',
        year: '2012',
        notes: ['AA Lifespan 2.0 MA550T', 'Acetal Standard', 'S1', 'C1K', 'M17SS-DBR', '445', 'F1 Aura+'],
        link: 'https://www.martinguitar.com/guitars/discontinued/HD-28E-Retro.html',
        image: true,
        serial: '1633689',
        production_year: 'October 2012',
        location: 'Nazareth, Pennsylvania, USA',
        featured: true,
    },
    {
        make: 'Martin',
        model: 'DX1',
        category: 'Instruments',
        type: 'Acoustic Guitar',
        year: '2000',
        notes: ['AA Lifespan 2.0 MA550T', 'Acetal Standard', 'S1', 'C1K', 'M17SS-DBR', 'Ellipse Matrix Blend'],
        image: true,
        serial: '728931',
        production_year: 'February 2000',
        location: 'Nazareth, Pennsylvania, USA',
    },
    {
        make: 'Traveler',
        model: 'Escape Mark III',
        category: 'Instruments',
        type: 'Acoustic Guitar',
        year: '2018',
        notes: ['AA Lifespan 2.0 MA530T', 'Acetal Standard', 'S1', 'C1K', 'Mahogany'],
        link: 'https://travelerguitar.com/products/escape-mark-3-mahogany',
        image: true,
        serial: 'M3-02910',
        featured: true,
    },
    {
        make: 'Yamaha',
        model: 'FG-230',
        category: 'Instruments',
        type: 'Acoustic Guitar',
        year: '1967',
        notes: ['12-string', 'Nippon Gakki', 'd. 2014'],
        link: 'https://usa.yamaha.com/products/musical_instruments/guitars_basses/ac_guitars/fg_fgx/index.html',
        image: true,
        serial: '726838',
        production_year: 'November 1967',
        location: 'Tenryu/Wada Factory, Japan',
        hide: true,
    },
    {
        make: 'Epiphone',
        model: 'Songmaker DR-100',
        category: 'Instruments',
        type: 'Acoustic Guitar',
        year: '2021',
        notes: ['AA Lifespan 2.0 MA550T', 'Ebony'],
        link: 'https://www.epiphone.com/en-US/Acoustic-Guitar/EPIKWM803/Ebony',
        image: true,
        serial: '', // TBD
        production_year: '',
        location: '',
        not_mine: true,
    },
    {
        make: 'Fender',
        model: 'MA-1',
        category: 'Instruments',
        type: 'Acoustic Guitar',
        year: '2014',
        notes: ['AA Lifespan 2.0 MA540T'],
        link: 'https://www.fender.com/en-US/acoustic-guitars/',
        image: true,
        serial: 'OI14087311',
        not_mine: true,
    },

    {
        make: 'Line 6',
        model: 'Variax 500',
        category: 'Instruments',
        type: 'Electric Guitar',
        year: '2003',
        notes: ['EXL110', 'Acetal Standard', 'S1', 'C1K', 'M17SS-BLK', 'S-Locks', 'GC-ELECTRIC-A'],
        link: 'https://line6.com/legacy/variax500',
        image: true,
        serial: '03058431',
        location: 'Korea',
        featured: true,
    },
    {
        make: 'Epiphone',
        model: 'S-310B',
        category: 'Instruments',
        type: 'Electric Guitar',
        year: '1987',
        notes: ['EXL110', 'Acetal Standard', 'S1', 'C1K', 'M17SS-BLK', 'S-Locks', 'GC-ELECTRIC-A', 'Spyder', 'Fat 50&rsquo;s'], // , 'Strat-style'
        image: true,
        serial: '1103087',
        location: 'Samick, Korea',
        featured: true,
    },
    {
        make: 'Epiphone',
        model: 'Les Paul Standard',
        category: 'Instruments',
        type: 'Electric Guitar',
        year: '2021',
        link: 'https://www.epiphone.com/en-US/Electric-Guitar/EPINA3562/Ebony',
        notes: ['EXL110', 'Acetal Standard', 'S1', 'C1K', 'M17SS-BLK', 'S-Locks', 'Standard \'60s Quilt Top', 'Translucent Blue'],
        image: true,
        serial: '21021527363', // local serial: 27363
        production_year: 'February 2021',
        location: 'Qingdao (electric), China',
    },
    {
        make: 'Epiphone',
        model: 'SG Standard',
        category: 'Instruments',
        type: 'Electric Guitar',
        year: '2023',
        link: 'https://www.epiphone.com/en-US/Electric-Guitar/EPIJ1X839/Heritage-Cherry',
        notes: ['EXL110', 'Heritage Cherry'],
        image: true,
        serial: '23051530731', // local serial: 30731
        production_year: 'May 2023',
        location: 'Qingdao (electric), China',
        not_mine: true,
    },
    {
        make: 'Washburn',
        model: 'X40',
        category: 'Instruments',
        type: 'Electric Guitar',
        year: '2002',
        notes: ['EXL110', 'Acetal Standard', 'S1', 'C1K', 'M17SS-BLK', 'S-Locks', 'GC-ELECTRIC-A'],
        link: 'https://www.washburn.com/instrument-style/double-cut-solid-body/',
        image: true,
        serial: '2110103',
        location: 'Korea',
    },
    {
        make: 'Daisy Rock',
        model: 'Daisy Short-Scale',
        category: 'Instruments',
        type: 'Electric Guitar',
        year: '2004',
        notes: ['22 1/2" scale', 'Awesome Blue'],
        image: true,
        serial: '207757',
        not_mine: true,
    },

    {
        make: 'Line 6',
        model: 'Variax 700',
        category: 'Instruments',
        type: 'Bass Guitar',
        year: '2004',
        notes: ['EXL170', 'Tortex Standard', 'MSS3-BRN', 'Straplok'],
        link: 'https://line6.com/legacy/variaxbass700',
        image: true,
        serial: '04101739',
        location: 'Korea',
        featured: true,
    },
    {
        make: 'Ibanez',
        model: 'Roadstar II RB650',
        category: 'Instruments',
        type: 'Bass Guitar',
        year: '1986',
        notes: ['EXL170', 'Tortex Standard', 'MSS3-BRN', 'Straplok'],
        link: 'https://www.ibanez.com/usa/products/category/electric_basses/',
        image: true,
        serial: 'A865503', // local serial: 5503
        production_year: 'January 1986',
        location: 'FujiGen Gakki, Japan',
    },
    {
        make: 'Schecter',
        model: 'Hellraiser Extreme-5',
        category: 'Instruments',
        type: 'Bass Guitar',
        year: '2021',
        notes: ['ECB81-5SL', 'Tortex Standard', 'MSS2-4-BLK', 'Straplok', 'SGR-6B'],
        link: 'https://www.schecterguitars.com/bass/hellraiser-extreme-2013-11-07/hellraiser-extreme-5-detail',
        image: true,
        serial: 'W21052189',
        production_year: '2021',
        location: 'South Korea',
        featured: true,
    },
//     {
//         make: 'Schecter',
//         model: 'C-5 Apocalypse',
//         category: 'Instruments',
//         type: 'Bass Guitar',
//         year: '2021',
//         link: 'https://www.schecterguitars.com/bass/apocalypse-series-1/c-5-apocalypse-rusty-grey-detail',
//         image: true,
//         serial: 'IW19030720', // DOA
//         production_year: '2019',
//         location: 'Indonesia',
//     },

    {
        make: 'Northfield',
        model: 'Calhoun',
        category: 'Instruments',
        type: 'Mandolin',
        year: '2018',
        notes: ['EFW74', 'Golden Gate MP-12', 'C5-R', 'C5K', 'M19PR-TAN', 'Mandolin Twin'],
        link: 'https://www.northfieldinstruments.com/thecalhoun',
        image: true,
        serial: 'FT180030',
        featured: true,
    },
    {
        make: 'Framus',
        model: 'Tenor Banjo',
        category: 'Instruments',
        type: 'Banjo',
        year: '1968', // ?
        notes: ['EXL110', 'Nylon Standard', 'C5-R', 'C5K', 'PM14-DBR', 'C-3770 Trailpak II', 'Irish Tenor tuning: 13/17/26/36'],
        image: true,
        serial: '27726-680',
    },
    {
        make: 'Wm. Schmick',
        model: 'Lyric Banjo',
        category: 'Instruments',
        type: 'Mandolin',
        year: '1920s?',
        notes: ['EJ74'],
        image: true,
        serial: 'unnumbered',
        production_year: 'Patented Sept. 23, 1914',
        location: 'Camden, NJ, USA',
    },
    {
        make: 'Kamoa',
        model: 'E3-S',
        category: 'Instruments',
        type: 'Ukulele',
        year: '2015', // ?
        notes: ['Soprano', 'GBE-UKE-SOP'],
        link: 'https://kamoaukuleles.myshopify.com/collections/kamoa-e3-s/products/kamoa-e3-s-soprano-red',
        image: true,
        serial: '12060058',
        location: 'China',
        featured: true,
    },

    {
        make: 'Hohner',
        model: 'Marine Band Deluxe',
        category: 'Instruments',
        type: 'Harmonica',
        notes: ['G', 'FlexRack'],
        year: '2020',
        link: 'https://www.hohner.de/en/instruments/harmonicas/diatonic/marine-band/marine-band-deluxe',
        image: true,
        featured: true,
    },
    {
        make: 'Hohner',
        model: 'Special 20',
        category: 'Instruments',
        type: 'Harmonica',
        notes: ['A', 'C', 'D', 'E', 'F', 'G', 'FlexRack'],
        year: 'various',
        link: 'https://www.hohner.de/en/instruments/harmonicas/diatonic/progressive/special-20',
        image: true,
        featured: true,
    },
    {
        make: 'Yamaha',
        model: 'YDP-223',
        category: 'Instruments',
        type: 'Keyboard',
        year: '2006',
        link: 'https://usa.yamaha.com/products/musical_instruments/pianos/arius/',
        image: true,
    },
    {
        make: 'Yamaha',
        model: 'YPT-300',
        category: 'Instruments',
        type: 'Keyboard',
        year: '2007',
        link: 'https://usa.yamaha.com/products/musical_instruments/keyboards/portable_keyboards/',
        image: true,
    },
    {
        make: 'Yamaha',
        model: 'DD-55C',
        category: 'Instruments',
        type: 'Drums',
        year: '2007',
        link: 'https://usa.yamaha.com/products/musical_instruments/drums/el_drums/digital_percussion/',
        image: true,
    },
    {
        make: 'Yamaha',
        model: 'Rydeen',
        category: 'Instruments',
        type: 'Drums',
        year: '2013', // ?
        link: 'https://usa.yamaha.com/products/musical_instruments/drums/ac_drums/drum_sets/rydeen/',
        notes: ['20&quot; bass', 'burgundy glitter'],
        image: true,
    },
//     {
//         make: 'Tama',
//         model: 'HS10 Swingstar',
//         category: 'Stands etc.',
//         type: 'Snare Drum Stand',
//         year: '2007',
//         link: 'https://www.tama.com/usa/products/category/hardware/',
//         image: true,
//     },
    {
        make: 'Meinl',
        model: 'HCS 14&quot; Crash',  
        category: 'Instruments',
        type: 'Cymbal',
        year: '2013', // ?
        link: 'https://meinlcymbals.com/en/products/hcs14c-m3486.html',
        image: true,
    },
    {
        make: 'Zildjian',
        model: 'Planet Z 18&quot; Crash Ride',  
        category: 'Instruments',
        type: 'Cymbal',
        year: '2013', // ?
        link: 'https://zildjian.com/18-planet-z-crash-ride.html',
        image: true,
    },
    {
        make: 'Zildjian',
        model: 'Planet Z 13&quot; Hi-Hat',  
        category: 'Instruments',
        type: 'Cymbal',
        year: '2013', // ?
        link: 'https://zildjian.com/13-planet-z-hihats-pair.html',
        image: true,
    },
    {
        make: 'Adam',
        model: 'Bongos',  
        category: 'Instruments',
        type: 'Bongos',
        year: '2013', // ?
        notes: ['6&quot;', '7.25&quot;'],
        image: true,
    },
    {
        make: 'Meinl',
        model: 'JC50AB-B',  
        category: 'Instruments',
        type: 'Cajon',
        year: '2022',
        notes: ['Snare Cajon 50, Baltic Birch, Almond Birch'],
        link: 'https://meinlpercussion.com/en/products/jc50ab-b-m5746.html',
        image: true,
    },

    {
        make: 'Line 6',
        model: 'POD X3 Live',
        category: 'Hardware',
        type: 'Pedal',
        year: '2010',
        link: 'https://line6.com/legacy/podx3live',
        image: true,
        featured: true,
    },
    {
        make: 'BOSS',
        model: 'RC-2 Loop Station',
        category: 'Hardware',
        type: 'Pedal',
        year: '2006',
        link: 'https://www.boss.info/us/products/rc-2/',
        image: true,
    },
    {
        make: 'Quick-Lok',
        model: 'VP-2611',
        category: 'Hardware',
        type: 'Pedal',
        year: '2016',
        link: 'https://www.quiklok.com/product/vp-2611-mono-volume-pedal/',
        image: true,
    },
    {
        make: 'Pignose',
        model: '7-100',
        category: 'Hardware',
        type: 'Amplifier',
        year: '2000s',
        link: 'https://pignoseamps.com/product/legendary-7-100-portable-amp/',
        image: true,
    },
    {
        make: 'Yamaha',
        model: 'THR30II Wireless',
        category: 'Hardware',
        type: 'Amplifier',
        year: '2021',
        link: 'https://usa.yamaha.com/products/musical_instruments/guitars_basses/amps_accessories/thr-ii/',
        notes: ['G10'],
        image: true,
        featured: true,
    },
    {
        make: 'Line 6',
        model: 'G10',
        category: 'Hardware',
        type: 'Guitar Accessory',
        notes: 'wireless',
        year: '2021',
        link: 'https://line6.com/relay-wireless/g10-g10s/',
        image: true,
    },
    {
        make: 'Line 6',
        model: 'Spider IV 15',
        category: 'Hardware',
        type: 'Amplifier',
        year: '2015', // ?
        link: 'https://line6.com/spider-guitar-amp/amps/',
        image: true,
    },
    {
        make: 'Line 6',
        model: 'FBV Express',
        category: 'Hardware',
        type: 'Controller',
        year: '2015',
        link: 'https://line6.com/legacy/fbve',
        image: true,
    },
    {
        make: 'Electro-Harmonix',
        model: 'Nano Big Muff Pi',
        category: 'Hardware',
        type: 'Pedal',
        year: '2020',
        link: 'https://www.ehx.com/products/nano-big-muff-pi',
        image: true,
    },
    {
        make: 'Electro-Harmonix',
        model: 'Metal Muff',
        category: 'Hardware',
        type: 'Pedal',
        year: '2020',
        link: 'https://www.ehx.com/products/metal-muff',
        image: true,
    },
    {
        make: 'Electro-Harmonix',
        model: 'Deluxe Bass Big Muff Pi',
        category: 'Hardware',
        type: 'Pedal',
        year: '2021',
        link: 'https://www.ehx.com/products/deluxe-bass-big-muff-pi',
        image: true,
    },
    {
        make: 'Digitech',
        model: 'Digidelay',
        category: 'Hardware',
        type: 'Pedal',
        year: '2005',
        image: true,
    },
    {
        make: 'Blackstar',
        model: 'Fly 3',
        category: 'Hardware',
        type: 'Amplifier',
        year: '2020',
        link: 'https://www.blackstaramps.com/uk/products/fly-3',
        image: true,
    },

    {
        make: 'Studio Projects',
        model: 'B1',
        category: 'Hardware',
        type: 'Microphone',
        year: '2004',
        link: 'http://www.studioprojects.com/b1.html',
        image: true,
    },
    {
        make: 'AKG',
        model: 'P220',
        category: 'Hardware',
        type: 'Microphone',
        year: '2021',
        link: 'https://www.akg.com/Microphones/Condenser%20Microphones/P220.html',
        image: true,
    },
    {
        make: 'Sennheiser',
        model: 'e 835',
        category: 'Hardware',
        type: 'Microphone',
        year: '2011',
        link: 'https://en-us.sennheiser.com/live-performance-microphone-vocal-stage-e-835',
        image: true,
    },
    {
        make: 'Shure',
        model: 'SM-58',
        category: 'Hardware',
        type: 'Microphone',
        year: '2007',
        link: 'https://www.shure.com/en-US/products/microphones/sm58',
        image: true,
    },

    {
        make: 'Edirol',
        model: 'MA-20D',
        category: 'Hardware',
        type: 'Monitors',
        year: '2004',
        image: true,
    },
    {
        make: 'Audio Technica',
        model: 'ATH-M40fs',
        category: 'Hardware',
        type: 'Headphones',
        year: '2004',
        link: 'https://www.audio-technica.com/en-us/ath-m40fs',
        image: true,
    },
    {
        make: 'Sony',
        model: 'MDR-V600',
        category: 'Hardware',
        type: 'Headphones',
        year: '1999',
        link: 'https://www.sony.com/electronics/headphones/t/headband-headphones',
        image: true,
    },
    {
        make: 'Shure',
        model: 'SE215-CL',
        category: 'Hardware',
        type: 'Headphones',
        year: '2021',
        link: 'https://www.shure.com/en-US/products/earphones/se215cl',
        image: true,
    },
    {
        make: 'Mackie',
        model: 'Big Knob',
        category: 'Hardware',
        type: 'Mixer',
        year: '2014',
        link: 'https://mackie.com/products/big-knob-series-monitor-controllers-interfaces',
        image: true,
    },
    {
        make: 'Yamaha',
        model: 'STAGEPAS 500',
        category: 'Hardware',
        type: 'PA',
        year: '2011',
        link: 'https://usa.yamaha.com/products/proaudio/pa_systems/',
        image: true,
    },

    {
        make: 'Focusrite',
        model: 'Scarlett 2i2',
        category: 'Hardware',
        type: 'Interface',
        year: '2021',
        notes: ['Gen3', 'USB'],
        link: 'https://focusrite.com/en/usb-audio-interface/scarlett/scarlett-2i2',
        image: true,
    },
    {
        make: 'Focusrite',
        model: 'Scarlett 18i20',
        category: 'Hardware',
        type: 'Interface',
        year: '2016',
        notes: ['Gen2', 'USB'],
        link: 'https://focusrite.com/en/usb-audio-interface/scarlett/scarlett-18i20',
        image: true,
    },
    {
        make: 'MOTU',
        model: '828mkII',
        category: 'Hardware',
        type: 'Interface',
        year: '2005',
        notes: 'FireWire',
        link: 'https://www.motu.com/products/motuaudio/828/',
        image: true,
    },
    {
        make: 'M-Audio',
        model: 'Oxygen8',
        category: 'Hardware',
        type: 'Controller',
        year: '2004',
        notes: 'USB',
        image: true,
    },
    {
        make: 'IK Multimedia',
        model: 'iRig',
        category: 'Hardware',
        type: 'Controller',
        year: '2011',
        image: true,
    },

    {
        make: 'Korg',
        model: 'DTR-2000',
        category: 'Hardware',
        type: 'Tuner',
        year: '2005',
        notes: 'rackmount',
        link: 'https://www.korg.com/us/products/tuners/',
        image: true,
    },
    {
        make: 'Korg',
        model: 'Sledgehammer Pro',
        category: 'Hardware',
        type: 'Tuner',
        year: '2019',
        notes: 'Clip-on',
        link: 'https://www.korg.com/us/products/tuners/sledgehammer_pro/',
        image: true,
    },

    {
        make: 'BOSS',
        model: 'FS-5U',
        category: 'Hardware',
        type: 'Controller',
        year: '2007',
        link: 'https://www.boss.info/us/products/fs-5u_5l/',
        image: true,
    },
    {
        make: 'O.C. White',
        model: 'ProBoom Deluxe',
        category: 'Stands etc.',
        type: 'Microphone Stand',
        year: '2006',
        link: 'https://www.ocwhite.com/broadcast-arms/proboom.html',
        image: true,
    },
    {
        make: 'Furman',
        model: 'PM-8 II',
        category: 'Hardware',
        type: 'Rack Hardware',
        notes: 'power conditioner',
        year: '2005',
        image: true,
    },
    {
        make: 'Furman',
        model: 'PB-48',
        category: 'Hardware',
        type: 'Rack Hardware',
        notes: 'patch bay',
        year: '2005',
        image: true,
    },
    {
        make: 'SKB',
        model: 'SKB-R8',
        category: 'Stands etc.',
        type: 'Rack',
        year: '2005',
        link: 'https://www.skbcases.com/music/products/proddetail.php?f=&id=819&o=&offset=4&c=80&s=80',
        image: true,
    },

    {
        make: 'Schecter',
        model: 'SGR-6B',
        category: 'Stands etc.',
        type: 'Instrument Case',
        year: '2021',
        notes: ['bass guitar'],
        link: 'https://www.schecterguitars.com/accessories/bass-cases/sgr-6b-c-shape-bass-hardcase-detail',
        image: true,
    },
//     {
//         make: 'Gator',
//         model: 'GTSA-GTRBASS',
//         category: 'Stands etc.',
//         type: 'Instrument Case',
//         year: '2021',
//         notes: ['bass guitar'],
//         link: 'https://www.gatorcases.com/products/guitar/instrument-bassguitar/tsa-ata-guitar-cases/tsa-guitar/bass-guitar-case-gtsa-gtrbass/',
//         image: true,
//     },
    {
        make: 'Gator',
        model: 'GC-ELECTRIC-A',
        category: 'Stands etc.',
        type: 'Instrument Case',
        year: '2005',
        notes: ['electric guitar'],
        link: 'https://www.gatorcases.com/products/guitar/molded-guitar-cases/gc-guitar/electric-guitar-case-gc-electric-a/',
        image: true,
    },
    {
        make: 'Gator',
        model: 'GBE-UKE-SOP',
        category: 'Stands etc.',
        type: 'Instrument Case',
        year: '2015',
        notes: ['ukulele'],
        link: 'https://www.gatorcases.com/products/guitar/gig-bags/gbe/soprano-ukulele-gig-bag-gbe-uke-sop/',
        image: true,
    },
    {
        make: 'Road Runner',
        model: 'RR3EG',
        category: 'Stands etc.',
        type: 'Instrument Case',
        year: '2021',
        notes: ['electric guitar'],
        link: 'https://roadrunnercases.com/rr3eg-electric-guitar-gig-bag/',
        image: true,
    },
    {
        make: 'Martin',
        model: '445',
        category: 'Stands etc.',
        type: 'Instrument Case',
        year: '2012',
        notes: ['acoustic guitar'],
        image: true,
    },
    {
        make: 'Superior',
        model: 'C-3770 Trailpak II',
        category: 'Stands etc.',
        type: 'Instrument Case',
        year: '2018',
        notes: ['mandolin'],
        image: true,
    },


    {
        make: 'Roc-N-Soc',
        model: 'Nitro',
        category: 'Stands etc.',
        type: 'Furniture',
        year: '2000s',
        link: 'https://rocnsoc.com/new/product-line/nitro-throne',
        image: true,
    },
    {
        make: 'Wittner',
        model: '801m',
        category: 'Hardware',
        type: 'Metronome',
        year: '2007',
        link: 'https://wittner-gmbh.de/wittner_metronome_maelzel_wooden_casing.html',
        image: true,
    },
    {
        make: 'String Swing',
        model: 'CC01K',
        category: 'Stands etc.',
        type: 'Instrument Stand',
        notes: ['guitar'],
        link: 'https://www.stringswing.com/product/cc01k-hardwood-home-studio-guitar-keeper-wall-mounted-guitar-hanger',
        image: true,
    },
    {
        make: 'Warwick',
        model: 'RS 20861',
        category: 'Stands etc.',
        type: 'Instrument Stand',
        notes: ['guitar'],
        year: '2007',
        link: 'https://shopframuswarwickusa.com/collections/rockstand/products/rockstand-multiple-guitar-stands?variant=40790902407320',
        image: true,
    },
    {
        make: 'Stagg',
        model: 'SUVM-A100BK',
        category: 'Stands etc.',
        type: 'Instrument Stand',
        notes: ['mandolin'],
        year: '2019',
        link: 'https://staggmusic.com/en/products/view/SUVMA100BK-foldable-a-stand-for-ukuleles-mandolins-and-violins/',
        image: true,
    },
    {
        make: 'Hohner',
        model: 'Harmonica Case',
        category: 'Stands etc.',
        type: 'Instrument Case',
        year: '2000',
        link: 'https://www.hohner.de/en/instruments/harmonicas/accessories/harmonica-case',
        image: true,
    },

//     {
//         make: 'Apple',
//         model: 'Logic Pro X',
//         category: 'Software',
//         type: 'Software',
//         link: 'https://www.apple.com/logic-pro/',
//     },
    {
        make: 'Apple',
        model: 'MacBook Pro',
        category: 'Hardware',
        type: 'Computer',
        year: '2020',
        link: 'https://www.apple.com/macbook-pro/',
        image: true,
    },
    {
        make: 'Apple',
        model: 'iPad Pro',
        category: 'Hardware',
        type: 'Computer',
        year: '2021',
        link: 'https://www.apple.com/ipad-pro/',
        image: true,
    },
//     {
//         make: 'Line 6',
//         model: 'POD Farm',
//         category: 'Software',
//         type: 'Software',
//         link: 'https://line6.com/podfarm/',
//     },

    {
        make: 'Clayton',
        model: 'Acetal Standard',
        category: 'Accessories',
        type: 'Pick',
        notes: ['.50mm/acoustic', '.80mm/electric'],
        link: 'https://www.steveclayton.com/acetal.php',
        image: true,
    },
    {
        make: 'Dunlop',
        model: 'Tortex Standard',
        category: 'Accessories',
        type: 'Pick',
        notes: ['1.14mm/bass'],
        link: 'https://www.jimdunlop.com/tortex-standard-pick-1-14mm/',
        image: true,
    },
    {
        make: 'Dunlop',
        model: 'Nylon Standard',
        category: 'Accessories',
        type: 'Pick',
        notes: ['.6mm/banjo'],
        link: 'https://www.jimdunlop.com/nylon-standard-pick-60mm/',
        image: true,
    },
    {
        make: 'Dunlop',
        model: 'Big Stubby',
        category: 'Accessories',
        type: 'Pick',
        notes: ['2.0mm/bass'],
        link: 'https://www.jimdunlop.com/big-stubby-pick-2-00mm/',
        hide: true,
        image: true,
    },
    {
        make: 'Saga',
        model: 'Golden Gate MP-12',
        category: 'Accessories',
        type: 'Pick',
        notes: ['mandolin'],
        link: 'https://www.sagamusic.com/shop/fretted-instrument-accessories/golden-gate-accessories/golden-gate-mp-12-deluxe-tortoise-style-flat-pick-rounded-triangle-extra-stiff-dozen/',
        image: true,
    },
    {
        make: 'Thalia',
        model: 'Pick Puck',
        category: 'Accessories',
        type: 'Guitar Accessory',
        year: '2022',
        link: 'https://www.thaliacapos.com/collections/pick-pucks',
        image: true,
    },

    {
        make: 'Shubb',
        model: 'S1',
        category: 'Accessories',
        type: 'Capo',
        year: '2000',
        notes: ['guitar'],
        link: 'https://shubb.com/product/deluxe-capo-s1/',
        image: true,
    },
    {
        make: 'Shubb',
        model: 'C1K',
        category: 'Accessories',
        type: 'Capo',
        year: '2021',
        notes: ['guitar'],
        link: 'https://shubb.com/product/capo-noir-c1k/',
        image: true,
    },
    {
        make: 'Shubb',
        model: 'C5-R',
        category: 'Accessories',
        type: 'Capo',
        year: '2019',
        notes: ['banjo', 'mandolin'],
        link: 'https://shubb.com/product/standard-capo-c5/',
        image: true,
    },
    {
        make: 'Shubb',
        model: 'C5K',
        category: 'Accessories',
        type: 'Capo',
        year: '2021',
        notes: ['banjo', 'mandolin'],
        link: 'https://shubb.com/product/capo-noir-c5k/',
        image: true,
    },
    {
        make: 'Shubb',
        model: 'Axys',
        category: 'Accessories',
        type: 'Guitar Accessory',
        notes: 'slide',
        year: '2007',
        link: 'https://shubb.com/',
        image: true,
    },
    {
        make: 'EBow',
        model: 'EBow',
        category: 'Accessories',
        type: 'Guitar Accessory',
        notes: 'ebow',
        year: '2000',
        image: true,
    },

    {
        make: 'Hohner',
        model: 'FlexRack',
        category: 'Stands etc.',
        type: 'Instrument Stand',
        notes: ['harmonica'],
        year: '2016',
        link: 'https://www.hohner.de/en/instruments/harmonicas/accessories/flexrack',
        image: true,
    },

    {
        make: 'Levys',
        model: 'M17SS-DBR',
        category: 'Accessories',
        type: 'Strap',
        year: '2013',
        link: 'https://www.levysleathers.com/product/guitar-strap-m17ss/',
        image: true,
    },
    {
        make: 'Levys',
        model: 'M17SS-BLK',
        category: 'Accessories',
        type: 'Strap',
        year: '2013',
        link: 'https://www.levysleathers.com/product/guitar-strap-m17ss-blk/',
        image: true,
        notes: ['S-Locks'],
    },
    {
        make: 'Levys',
        model: 'M19PR-TAN',
        category: 'Accessories',
        type: 'Strap',
        year: '2019',
        link: 'https://www.levysleathers.com/product/mandolin-strap-m19pr/',
        image: true,
    },
    {
        make: 'Levys',
        model: 'MSS3-BRN',
        category: 'Accessories',
        type: 'Strap',
        year: '2010',
        link: 'https://www.levysleathers.com/product/guitar-strap-mss3-brn/',
        image: true,
        notes: ['Straplok'],
    },
    {
        make: 'Levys',
        model: 'MSS2-4-BLK',
        category: 'Accessories',
        type: 'Strap',
        year: '2021',
        link: 'https://www.levysleathers.com/product/guitar-strap-mss2-4-blk/',
        image: true,
        notes: ['Straplok'],
    },
    {
        make: 'Levys',
        model: 'PM14-DBR',
        category: 'Accessories',
        type: 'Strap',
        year: '2020',
        link: 'https://www.levysleathers.com/product/banjo-strap-pm14-dbr/',
        image: true,
    },
    {
        make: 'Dunlop',
        model: 'Straplok',
        category: 'Accessories',
        type: 'Strap Retainers',
        year: '2020',
        link: 'https://www.jimdunlop.com/straplok-strap-retainers-original-nickel/',
        image: true,
    },
    {
        make: 'Schaller',
        model: 'S-Locks',
        category: 'Accessories',
        type: 'Strap Retainers',
        year: '2000',
        link: 'https://schaller.info/en/slocks/',
        image: true,
    },

    {
        make: 'Hercules',
        model: 'MS531B',
        category: 'Stands etc.',
        type: 'Microphone Stand',
        year: '2017',
        link: 'https://herculesstands.com/us/products/microphone/boom/ms531b/',
        image: true,
    },
    {
        make: 'Gator',
        model: 'GFW-MIC-0822',
        category: 'Stands etc.',
        type: 'Microphone Stand',
        year: '2021',
        link: 'https://www.gatorframeworks.com/products/telescoping-boom-podcast-bass-drum-and-amp-mic-stand-gfw-mic-0822/',
        image: true,
    },
    {
        make: 'Stageline',
        model: 'GS550A',
        category: 'Stands etc.',
        type: 'Instrument Stand',
        notes: ['guitar'],
        year: '2013', // ?
        link: 'https://www.stagelinestands.com/product/gs550a-acoustic-guitar-stand/',
        image: true,
    },


    {
        make: 'Martin',
        model: 'AA Lifespan 2.0 MA550T',
        category: 'Accessories',
        type: 'Strings',
        notes: ['acoustic guitar', 'medium', '.013-.056', '92/8 phosphor bronze', 'acoustic'],
        link: 'https://www.martinguitar.com/strings/authentic-acoustic/martin-authentic-acoustic-lifespan-2.0-guitar-strings-92-8-phosphor-bronze.html', // SP Lifespan MSP7200
        image: true,
    },
    {
        make: 'Martin',
        model: 'AA Lifespan 2.0 MA540T',
        category: 'Accessories',
        type: 'Strings',
        notes: ['acoustic guitar', 'light', '.012-.054', '92/8 phosphor bronze', 'acoustic'],
        link: 'https://www.martinguitar.com/strings/authentic-acoustic/martin-authentic-acoustic-lifespan-2.0-guitar-strings-92-8-phosphor-bronze.html', // SP Lifespan MSP7100
        image: true,
    },
    {
        make: 'Martin',
        model: 'AA Lifespan 2.0 MA530T',
        category: 'Accessories',
        type: 'Strings',
        notes: ['acoustic guitar', 'extra light', '.010-.047', '92/8 phosphor bronze', 'acoustic'],
        link: 'https://www.martinguitar.com/strings/authentic-acoustic/martin-authentic-acoustic-lifespan-2.0-guitar-strings-92-8-phosphor-bronze.html', // SP Lifespan MSP7000
        image: true,
    },
//     {
//         make: 'GHS',
//         model: 'A250',
//         category: 'Accessories',
//         type: 'Strings',
//         notes: ['light', '.010-.036', 'phosphor bronze', 'mandolin'],
//         link: 'https://www.ghsstrings.com/products/11374-phosphor-bronze-mandolin/options/12146-loop-end-light',
//         image: true,
//     },
//     {
//         make: 'GHS',
//         model: 'A270',
//         category: 'Accessories',
//         type: 'Strings',
//         notes: ['medium', '.011-.040', 'phosphor bronze', 'mandolin'],
//         link: 'https://www.ghsstrings.com/products/11374-phosphor-bronze-mandolin/options/12146-loop-end-light',
//         image: true,
//     },
//     {
//         make: 'D&rsquo;Addario',
//         model: 'EJ73',
//         category: 'Accessories',
//         type: 'Strings',
//         notes: ['light', '.010-.038', 'phosphor bronze'],
//         link: 'https://www.daddario.com/products/guitar/mandolin/phosphor-bronze-mandolin/ej73-mandolin-phosphor-bronze-light-10-38/',
//         image: true,
//     },
    {
        make: 'D&rsquo;Addario',
        model: 'EJ74',
        category: 'Accessories',
        type: 'Strings',
        notes: ['mandolin', 'medium', '.011-.040', 'phosphor bronze'],
        link: 'https://www.daddario.com/products/guitar/mandolin/phosphor-bronze-mandolin/ej74-mandolin-phosphor-bronze-medium-11-40/',
        image: true,
    },
    {
        make: 'D&rsquo;Addario',
        model: 'EFW74',
        category: 'Accessories',
        type: 'Strings',
        notes: ['mandolin', 'medium', '.011-.036', 'flatwound'],
        link: 'https://www.daddario.com/products/guitar/mandolin/flatwound-mandolin/efw74-mandolin-flat-wound-medium-11-36/',
        image: true,
    },
    {
        make: 'D&rsquo;Addario',
        model: 'EXL110',
        category: 'Accessories',
        type: 'Strings',
        notes: ['guitar', 'banjo', 'light', '.010-.046', 'nickel'],
        link: 'https://www.daddario.com/products/guitar/electric-guitar/xl-nickel/exl110-nickel-wound-regular-light-10-46/',
        image: true,
    },
//     {
//         make: 'Ernie Ball',
//         model: 'Slinky Bass 2850',
//         category: 'Accessories',
//         type: 'Strings',
//         notes: ['super long', '.045-.130', 'nickel', 'roundwound', '5-string'],
//         link: 'https://www.ernieball.com/guitar-strings/bass-strings/slinky-nickel-wound-electric-bass-strings/long-scale#P02850',
//         image: true,
//     },
//     {
//         make: 'Ernie Ball',
//         model: 'Slinky Bass 2834',
//         category: 'Accessories',
//         type: 'Strings',
//         notes: ['long', '.045-.100', 'nickel', 'roundwound'],
//         link: 'https://www.ernieball.com/guitar-strings/bass-strings/slinky-nickel-wound-electric-bass-strings/4-strings#P02834',
//         image: true,
//     },
    {
        make: 'D&rsquo;Addario',
        model: 'EXL170',
        category: 'Accessories',
        type: 'Strings',
        notes: ['bass', 'long', '.045-.100', 'nickel', 'roundwound'],
        link: 'https://www.daddario.com/products/guitar/bass-guitar/xl-nickel-bass/exl170-nickel-wound-bass-light-45-100-long-scale/',
        image: true,
    },
    {
        make: 'D&rsquo;Addario',
        model: 'ECB81-5SL',
        category: 'Accessories',
        type: 'Strings',
        notes: ['bass', 'super long', '.045-.132', 'chrome', 'flatwound', '5-string'],
        link: 'https://www.daddario.com/products/guitar/bass-guitar/xl-chromes-bass/ecb81-5sl-chromes-bass-5-string-light-45-132-super-long-scale/',
        image: true,
    },

    {
        make: 'Fender',
        model: 'Fat 50&rsquo;s',
        category: 'Hardware',
        type: 'Pickup',
        year: '2004',
        link: 'https://shop.fender.com/en-US/parts/stratocaster-parts/custom-shop-fat-50s-stratocaster-pickups/0992113000.html',
        image: true,
    },
    {
        make: 'Fishman',
        model: 'Ellipse Matrix Blend',
        category: 'Hardware',
        type: 'Pickup',
        year: '2000s',
        link: 'https://www.fishman.com/product-series-matrix-pickup-systems/',
//         link: 'https://www.fishman.com/products/series/ellipse/ELLIPSE-MATRIX-BLEND-undersaddle-pickup/',
        image: true,
    },
    {
        make: 'Fishman',
        model: 'F1 Aura+',
        category: 'Hardware',
        type: 'Pickup',
        year: 2012,
        link: 'https://www.fishman.com/product-series-aura-imaging/',
//         link: 'https://www.fishman.com/fishman-equipped/f1-aura-oem/',
        image: true,
    },
    {
        make: 'Kahler',
        model: 'Spyder',
        category: 'Hardware',
        type: 'Guitar Accessory',
        notes: 'locking tremolo',
        year: '1987',
        link: 'https://www.kahlerusa.com',
        image: true,
    },
    {
        make: 'K&amp;K',
        model: 'Mandolin Twin',
        category: 'Hardware',
        type: 'Pickup',
        year: '2019',
        link: 'https://kksound.com/products/mandolintwin.php',
        image: true,
    },

    {
        make: 'Peavey',
        model: 'PV 6',
        category: 'Hardware',
        type: 'Mixer',
        year: '2006',
        link: 'https://peavey.com/products/mixers.cfm',
        hide: true,
        image: true,
    },
    {
        make: 'Tapco',
        model: 'Mix.50',
        category: 'Hardware',
        type: 'Mixer',
        year: '2008',
        hide: true,
        image: true,
    },
];

var links = {
    'AKG': 'https://www.akg.com/',
    'Apple': 'https://www.apple.com/',
    'Audio Technica': 'https://www.audio-technica.com/',
    'BOSS': 'https://www.boss.info/us/',
    'Blackstar': 'https://www.blackstaramps.com/',
    'Clayton': 'https://www.steveclayton.com/',
    'Daisy Rock': 'https://www.daisyrock.com/',
    'D&rsquo;Addario': 'https://www.daddario.com/',
    'Digitech': 'https://www.digitech.com/',
    'Dunlop': 'https://www.jimdunlop.com/',
    'Edirol': 'https://www.roland.com/',
    'Electro-Harmonix': 'https://www.ehx.com/',
    'Epiphone': 'https://www.epiphone.com/',
//     'Ernie Ball': 'https://www.ernieball.com/',
    'EBow': 'https://www.ebow.com/',
    'Fender': 'https://www.fender.com/',
    'Fishman': 'https://www.fishman.com/',
    'Framus': 'https://www.framus-vintage.de/en/modules/modells/modells5084.html?classID=5&typeID=1-8&katID=4673&cl=EN',
    'Focusrite': 'https://focusrite.com/',
    'Furman': 'https://www.furmanpower.com/',
    'Gator': 'https://www.gatorcases.com/',
    'GHS': 'https://www.ghsstrings.com/',
    'Hercules': 'http://herculesstands.com/',
    'Hohner': 'https://www.hohner.de/',
    'Ibanez': 'https://www.ibanez.com/',
    'IK Multimedia': 'https://www.ikmultimedia.com/',
    'Kamoa': 'https://kamoaukuleles.myshopify.com/',
    'K&amp;K': 'https://kksound.com/',
    'Kahler': 'https://www.kahlerusa.com/',
    'Korg': 'https://www.korg.com/',
    'Levys': 'https://www.levysleathers.com/',
    'Line 6': 'https://line6.com/',
    'M-Audio': 'https://www.m-audio.com/',
    'Mackie': 'https://www.mackie.com/',
    'Martin': 'https://www.martinguitar.com/',
    'Meinl': 'https://meinlcymbals.com/',
    'MOTU': 'https://www.motu.com/',
    'Northfield': 'https://www.northfieldinstruments.com/',
    'O.C. White': 'https://www.ocwhite.com/',
    'Peavey': 'https://peavey.com/',
    'Pignose': 'https://pignoseamps.com/',
    'Quick-Lok': 'https://www.quiklok.com/',
    'Road Runner': 'https://roadrunnercases.com/',
    'Roc-N-Soc': 'https://rocnsoc.com/',
    'Saga': 'https://www.sagamusic.com/',
    'Schaller': 'https://schaller.info/',
    'Schecter': 'https://www.schecterguitars.com/',
    'Sennheiser': 'https://en-us.sennheiser.com/',
    'Shubb': 'https://www.shubb.com/',
    'Shure': 'https://www.shure.com/',
    'SKB': 'https://www.skbcases.com/',
    'Sony': 'https://www.sony.com/',
    'Stagg': 'https://staggmusic.com/',
    'Stageline': 'https://www.stagelinestands.com/',
    'String Swing': 'https://www.stringswing.com/',
    'Studio Projects': 'http://www.studioprojects.com/',
//     'Tama': 'https://www.tama.com/',
    'Tapco': 'https://www.mackie.com/',
    'Thalia': 'https://www.thaliacapos.com/collections/pick-pucks',
    'Traveler': 'https://travelerguitar.com/',
    'Warwick': 'https://www.warwick.de/en/Warwick-.html',
    'Washburn': 'https://www.washburn.com/',
    'Wittner': 'https://www.wittner-gmbh.de/',
    'Yamaha': 'https://usa.yamaha.com/',
    'Zildjian': 'https://zildjian.com/',
};
